#Pulls a file called 'creds.json' generated by AWS Secrets Manager that contains the Google Service accounts credentials json file, as well as a json file containing the relevant Twitter developer credentials required for the app (ACCESS_TOKEN, ACCESS_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_SECRET)

import json

def main():
	with open('creds.json') as f:
		x = json.load(f)
	google = json.loads(x['GOOGLE_SERVICE_ACCOUNT'])
	twitter = json.loads(x['TWITTER_CREDS'])
	with open('google_service_account.json', 'w') as fp:
		json.dump(google, fp)
	with open('twitter_creds.json', 'w') as fp:
		json.dump(twitter, fp)

if __name__ == "__main__":
    main()